name: Sync Garmin to Notion

on:
  schedule:
    # Run twice daily at 9 AM and 9 PM Eastern Time (2 AM and 2 PM UTC)
    - cron: '0 2,14 * * *'
  workflow_dispatch:
env:
  TZ: 'America/Montreal'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Run Garmin Activities Sync
        env:
          GARMIN_EMAIL: ${{ secrets.GARMIN_EMAIL }}
          GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
          TZ: 'America/Montreal'
        run: python garmin-activities.py

      - name: Run Daily Steps Sync
        env:
          GARMIN_EMAIL: ${{ secrets.GARMIN_EMAIL }}
          GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
          NOTION_PR_DB_ID: ${{ secrets.NOTION_PR_DB_ID }}
          NOTION_STEPS_DB_ID: ${{ secrets.NOTION_STEPS_DB_ID }}
          NOTION_WELLNESS_DB_ID: ${{ secrets.NOTION_WELLNESS_DB_ID }}
          TZ: 'America/Montreal'
        run: python daily-steps.py
